# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI/CD

on:
  workflow_dispatch:
  push:
  

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies + style
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        source $HOME/.poetry/env
        poetry install
        poetry run flake8 app
        poetry run mypy -p app

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker-build
      run: |
        docker build -t tlwywgt:$GITHUB_SHA .
        mkdir artifacts
        docker save tlwywgt:$GITHUB_SHA > artifacts/docker-image.tar

    - name: Temporarily save Docker image
      uses: actions/upload-artifact@v2
      with:
        name: docker-artifact
        path: artifacts
        retention-days: 1


  docker-run:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: artifacts

      - name: Docker load
        run: |
          docker load < artifacts/docker-image.tar
          


